# Generated by Django 3.1.7 on 2021-06-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_model', models.CharField(choices=[('OPTI International: GT 3000 (208V) 208V [CEC 2016]', 'OPTI International: GT 3000 (208V) 208V [CEC 2016]'), ('ABB: MICRO-0.25-I-OUTD-US-208 [208V] 208V [CEC 2018]', 'ABB: MICRO-0.25-I-OUTD-US-208 [208V] 208V [CEC 2018]'), ('SMA America: SB7000US 240V [CEC 2007]', 'SMA America: SB7000US 240V [CEC 2007]'), ('Satcon Technology: PVS-30 (480V) 480V [CEC 2016]', 'Satcon Technology: PVS-30 (480V) 480V [CEC 2016]')], max_length=200, null=True)),
                ('nominal_ac_voltage', models.IntegerField(max_length=10, null=True)),
                ('maximum_ac_power', models.IntegerField(max_length=10, null=True)),
                ('maximum_dc_power', models.FloatField(max_length=10, null=True)),
                ('nominal_dc_voltage', models.FloatField(max_length=10, null=True)),
                ('power_consumption_during_operation', models.FloatField(max_length=10, null=True)),
                ('power_consumption_at_night', models.FloatField(max_length=10, null=True)),
                ('maximum_dc_voltage', models.IntegerField(max_length=10, null=True)),
                ('maximum_dc_current', models.FloatField(max_length=10, null=True)),
                ('minimum_mppt_dc_voltage', models.IntegerField(max_length=10, null=True)),
                ('maximum_mppt_dc_voltage', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photovoltaic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=8, null=True)),
                ('pv_model', models.CharField(choices=[('A10Green Technology A10J-M60-235', 'A10Green Technology A10J-M60-235'), ('Neo Solar Power D6M350E4AME', 'Neo Solar Power D6M350E4AME'), ('A10Green Technology A10J-M60-220', 'A10Green Technology A10J-M60-220'), ('LG Electronics LG345S2W-A5', 'LG Electronics LG345S2W-A5')], max_length=300, null=True)),
                ('rated_power', models.IntegerField(max_length=10, null=True)),
                ('number_of_modules', models.IntegerField(max_length=8, null=True)),
                ('b_i_p_v', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('width', models.FloatField(max_length=10, null=True)),
                ('length', models.IntegerField(max_length=10, null=True)),
                ('inverter_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.inverter')),
            ],
        ),
    ]
