# Generated by Django 3.1.7 on 2021-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='inverter_model',
            field=models.CharField(choices=[('OPTI International: GT 3000 (208V) 208V [CEC 2016]', 'OPTI International: GT 3000 (208V) 208V [CEC 2016]'), ('ABB: MICRO-0.25-I-OUTD-US-208 [208V] 208V [CEC 2018]', 'ABB: MICRO-0.25-I-OUTD-US-208 [208V] 208V [CEC 2018]'), ('Satcon Technology: PVS-30 (480V) 480V [CEC 2016]', 'Satcon Technology: PVS-30 (480V) 480V [CEC 2016]'), ('SMA America: SB7000US 240V [CEC 2007]', 'SMA America: SB7000US 240V [CEC 2007]')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='pv_model',
            field=models.CharField(choices=[('LG Electronics LG345S2W-A5', 'LG Electronics LG345S2W-A5'), ('A10Green Technology A10J-M60-220', 'A10Green Technology A10J-M60-220'), ('A10Green Technology A10J-M60-235', 'A10Green Technology A10J-M60-235'), ('Neo Solar Power D6M350E4AME', 'Neo Solar Power D6M350E4AME')], max_length=300, null=True),
        ),
    ]
