# Generated by Django 3.2.6 on 2021-08-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='photovoltaic',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='photovoltaic',
            name='envelope_selection',
        ),
        migrations.RemoveField(
            model_name='photovoltaic',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='photovoltaic',
            name='inverter_model',
        ),
        migrations.RemoveField(
            model_name='photovoltaic',
            name='non_vertical_surface_solar_attenuation_rate',
        ),
        migrations.RemoveField(
            model_name='photovoltaic',
            name='number_of_modules',
        ),
        migrations.RemoveField(
            model_name='photovoltaic',
            name='total_equipment_cost',
        ),
        migrations.RemoveField(
            model_name='radiation',
            name='inverter_model',
        ),
        migrations.RemoveField(
            model_name='radiation',
            name='pv_model',
        ),
        migrations.AlterField(
            model_name='inverter',
            name='inverter_model',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='pv_model',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='rated_power',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='azimuth',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='correction_rate',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='day',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='month',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='radiations',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='slope',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='time',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='InverterCategory',
        ),
        migrations.DeleteModel(
            name='PvCategory',
        ),
        migrations.AlterField(
            model_name='radiation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.location'),
        ),
    ]
