# Generated by Django 3.2.6 on 2021-08-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_auto_20210820_0640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photovoltaic',
        ),
    ]
