# Generated by Django 3.1.7 on 2021-06-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_auto_20210611_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='inverter_model',
            field=models.CharField(choices=[('SMA America: SB7000US 240V [CEC 2007]', 'SMA America: SB7000US 240V [CEC 2007]'), ('OPTI International: GT 3000 (208V) 208V [CEC 2016]', 'OPTI International: GT 3000 (208V) 208V [CEC 2016]'), ('ABB: MICRO-0.25-I-OUTD-US-208 [208V] 208V [CEC 2018]', 'ABB: MICRO-0.25-I-OUTD-US-208 [208V] 208V [CEC 2018]'), ('Satcon Technology: PVS-30 (480V) 480V [CEC 2016]', 'Satcon Technology: PVS-30 (480V) 480V [CEC 2016]')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='pv_model',
            field=models.CharField(choices=[('LG Electronics LG345S2W-A5', 'LG Electronics LG345S2W-A5'), ('A10Green Technology A10J-M60-220', 'A10Green Technology A10J-M60-220'), ('Neo Solar Power D6M350E4AME', 'Neo Solar Power D6M350E4AME'), ('A10Green Technology A10J-M60-235', 'A10Green Technology A10J-M60-235')], max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, null=True)),
                ('slope', models.FloatField(max_length=10, null=True)),
                ('azimuth', models.IntegerField(max_length=10, null=True)),
                ('radiations', models.FloatField(max_length=10, null=True)),
                ('correction_rate', models.FloatField(max_length=10, null=True)),
                ('month', models.CharField(max_length=10, null=True)),
                ('day', models.IntegerField(max_length=10, null=True)),
                ('time', models.TimeField(max_length=10, null=True)),
                ('inverter_model', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.inverter')),
                ('pv_model', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.photovoltaic')),
            ],
        ),
    ]
