# Generated by Django 3.2.6 on 2021-08-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_delete_photovoltaic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photovoltaic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_model', models.CharField(max_length=500)),
                ('rated_power', models.IntegerField(max_length=10, null=True)),
                ('b_i_p_v', models.CharField(max_length=4)),
                ('width', models.FloatField(max_length=10)),
                ('length', models.IntegerField(max_length=10)),
            ],
        ),
    ]
