# Generated by Django 3.2.6 on 2021-08-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_photovoltaic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Radiation',
        ),
    ]
