# Generated by Django 3.1.7 on 2021-06-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_auto_20210629_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='maximum_ac_power',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='maximum_dc_current',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='maximum_dc_power',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='maximum_dc_voltage',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='maximum_mppt_dc_voltage',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='minimum_mppt_dc_voltage',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='nominal_ac_voltage',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='nominal_dc_voltage',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='power_consumption_at_night',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='power_consumption_during_operation',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('South Roof', 'South Roof'), ('North Roof', 'North Roof'), ('East Roof', 'East Roof'), ('West Roof', 'West Roof')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='facility_name',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='inverter_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.invertercategory'),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='length',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='non_vertical_surface_solar_attenuation_rate',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='number_of_modules',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='pv_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.pvcategory'),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='rated_power',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='total_equipment_cost',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='width',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='azimuth',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='correction_rate',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='day',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='inverter_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.invertercategory'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.location'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='month',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='pv_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.pvcategory'),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='radiations',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='slope',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='time',
            field=models.TimeField(max_length=10, null=True),
        ),
    ]
