# Generated by Django 3.2.6 on 2021-08-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_delete_radiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope', models.FloatField(max_length=10, null=True)),
                ('azimuth', models.IntegerField(max_length=10, null=True)),
                ('radiations', models.FloatField(max_length=10, null=True)),
                ('correction_rate', models.FloatField(max_length=10, null=True)),
                ('month', models.IntegerField(max_length=10, null=True)),
                ('day', models.IntegerField(max_length=10, null=True)),
                ('time', models.IntegerField(max_length=10, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.location')),
            ],
        ),
    ]
