# Generated by Django 3.1.7 on 2021-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_auto_20210630_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiation',
            name='inverter_model',
        ),
        migrations.RemoveField(
            model_name='radiation',
            name='pv_model',
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('North', 'North'), ('East', 'East'), ('South', 'South'), ('West', 'West')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('East Roof', 'East Roof'), ('North Roof', 'North Roof'), ('South Roof', 'South Roof'), ('West Roof', 'West Roof')], max_length=10, null=True),
        ),
    ]
