# Generated by Django 3.2.6 on 2021-08-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_radiation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inverter',
        ),
    ]
