# Generated by Django 3.1.7 on 2021-07-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_auto_20210702_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('East Roof', 'East Roof'), ('West Roof', 'West Roof'), ('South Roof', 'South Roof'), ('North Roof', 'North Roof')], max_length=10, null=True),
        ),
    ]
