# Generated by Django 3.2.6 on 2021-08-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_delete_inverter'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PvCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_ac_voltage', models.IntegerField(max_length=10)),
                ('maximum_ac_power', models.IntegerField(max_length=10)),
                ('maximum_dc_power', models.FloatField(max_length=10)),
                ('nominal_dc_voltage', models.FloatField(max_length=10)),
                ('power_consumption_during_operation', models.FloatField(max_length=10)),
                ('power_consumption_at_night', models.FloatField(max_length=10)),
                ('maximum_dc_voltage', models.IntegerField(max_length=10)),
                ('maximum_dc_current', models.FloatField(max_length=10)),
                ('minimum_mppt_dc_voltage', models.IntegerField(max_length=10)),
                ('maximum_mppt_dc_voltage', models.IntegerField(max_length=10)),
                ('inverter_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.invertercategory')),
            ],
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='pv_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.pvcategory'),
        ),
    ]
