# Generated by Django 3.1.7 on 2021-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0009_auto_20210716_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('East', 'East'), ('South', 'South'), ('North', 'North'), ('West', 'West')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('South Roof', 'South Roof'), ('North Roof', 'North Roof'), ('East Roof', 'East Roof'), ('West Roof', 'West Roof')], max_length=10, null=True),
        ),
    ]
