# Generated by Django 3.1.7 on 2021-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0013_auto_20210717_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('North', 'North'), ('West', 'West'), ('South', 'South'), ('East', 'East')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('East Roof', 'East Roof'), ('West Roof', 'West Roof'), ('North Roof', 'North Roof'), ('South Roof', 'South Roof')], max_length=10, null=True),
        ),
    ]
