# Generated by Django 3.1.7 on 2021-07-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0015_auto_20210718_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('North Roof', 'North Roof'), ('West Roof', 'West Roof'), ('South Roof', 'South Roof'), ('East Roof', 'East Roof')], max_length=10, null=True),
        ),
    ]
