# Generated by Django 3.1.7 on 2021-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0017_auto_20210725_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('South Roof', 'South Roof'), ('West Roof', 'West Roof'), ('East Roof', 'East Roof'), ('North Roof', 'North Roof')], max_length=10, null=True),
        ),
    ]
