# Generated by Django 3.1.7 on 2021-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0020_auto_20210727_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('East', 'East'), ('South', 'South'), ('West', 'West'), ('North', 'North')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('West Roof', 'West Roof'), ('North Roof', 'North Roof'), ('South Roof', 'South Roof'), ('East Roof', 'East Roof')], max_length=10, null=True),
        ),
    ]
