# Generated by Django 3.1.7 on 2021-07-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0021_auto_20210727_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('East Roof', 'East Roof'), ('West Roof', 'West Roof'), ('South Roof', 'South Roof'), ('North Roof', 'North Roof')], max_length=10, null=True),
        ),
    ]
