# Generated by Django 3.1.7 on 2021-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0022_auto_20210727_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('South', 'South'), ('North', 'North')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('East Roof', 'East Roof'), ('North Roof', 'North Roof'), ('West Roof', 'West Roof'), ('South Roof', 'South Roof')], max_length=10, null=True),
        ),
    ]
