# Generated by Django 3.1.7 on 2021-07-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0025_auto_20210727_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('West Roof', 'West Roof'), ('North Roof', 'North Roof'), ('East Roof', 'East Roof'), ('South Roof', 'South Roof')], max_length=10, null=True),
        ),
    ]
