# Generated by Django 3.1.7 on 2021-07-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0026_auto_20210727_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('East', 'East'), ('North', 'North'), ('West', 'West'), ('South', 'South')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('East Roof', 'East Roof'), ('South Roof', 'South Roof'), ('North Roof', 'North Roof'), ('West Roof', 'West Roof')], max_length=10, null=True),
        ),
    ]
