# Generated by Django 3.1.7 on 2021-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0029_auto_20210727_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('West', 'West'), ('North', 'North'), ('East', 'East'), ('South', 'South')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('North Roof', 'North Roof'), ('East Roof', 'East Roof'), ('South Roof', 'South Roof'), ('West Roof', 'West Roof')], max_length=10, null=True),
        ),
    ]
