# Generated by Django 3.1.7 on 2021-07-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0030_auto_20210727_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('East', 'East'), ('North', 'North'), ('West', 'West'), ('South', 'South')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('North Roof', 'North Roof'), ('East Roof', 'East Roof'), ('West Roof', 'West Roof'), ('South Roof', 'South Roof')], max_length=10, null=True),
        ),
    ]
