# Generated by Django 3.1.7 on 2021-07-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0035_auto_20210728_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('East', 'East'), ('South', 'South'), ('North', 'North'), ('West', 'West')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('North Roof', 'North Roof'), ('South Roof', 'South Roof'), ('West Roof', 'West Roof'), ('East Roof', 'East Roof')], max_length=10, null=True),
        ),
    ]
