# Generated by Django 3.1.7 on 2021-07-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0036_auto_20210728_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('North', 'North'), ('East', 'East'), ('South', 'South'), ('West', 'West')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('East Roof', 'East Roof'), ('South Roof', 'South Roof'), ('West Roof', 'West Roof'), ('North Roof', 'North Roof')], max_length=10, null=True),
        ),
    ]
