# Generated by Django 3.1.7 on 2021-07-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0038_auto_20210728_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='b_i_p_v',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('South', 'South'), ('West', 'West'), ('North', 'North'), ('East', 'East')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('East Roof', 'East Roof'), ('North Roof', 'North Roof'), ('South Roof', 'South Roof'), ('West Roof', 'West Roof')], max_length=10, null=True),
        ),
    ]
