# Generated by Django 3.1.7 on 2021-07-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0039_auto_20210729_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaic',
            name='direction',
            field=models.CharField(choices=[('South', 'South'), ('North', 'North'), ('West', 'West'), ('East', 'East')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photovoltaic',
            name='envelope_selection',
            field=models.CharField(choices=[('North Roof', 'North Roof'), ('East Roof', 'East Roof'), ('West Roof', 'West Roof'), ('South Roof', 'South Roof')], max_length=10, null=True),
        ),
    ]
